1. install and import Dependencies
    * go to pytorch website and choose the version: https://pytorch.org/

In [1]:
!pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |█████████████                   | 834.1 MB 1.2 MB/s eta 0:16:26tcmalloc: large alloc 1147494400 bytes == 0x55e9a6b30000 @  0x7f3b7127d615 0x55e96e33c02c 0x55e96e41c17a 0x55e96e33ee4d 0x55e96e430c0d 0x55e96e3b30d8 0x55e96e3adc35 0x55e96e34073a 0x55e96e3b2f40 0x55e96e3adc35 0x55e96e34073a 0x55e96e3af93b 0x55e96e431a56 0x55e96e3aefb3 0x55e96e431a56 0x55e96e3aefb3 0x55e96e431a56 0x55e96e3aefb3 0x55e96e340b99 0x55e96e383e79 0x55e96e33f7b2 0x55e96e3b2e65 0x55e96e3adc35 0x55e96e34073a 0x55e96e3af93b 0x55e96e3adc35 0x55e96e34073a 0x55e96e3aeb0e 0x55e96e34065a 0x55e96e3aed67 0x55e96e3adc35
     |████████████████▌               | 1055.7 MB 1.4 MB/s eta 0:11:47tcmalloc: large alloc 1434370048 bytes == 0x55e9eb186000 @  0x7f3b7127d615 0x55e96e33c02c 0x55e96e41c17a 0x55e96e33ee4d 0x55e96e430c0d 0x55e96e3b30d8 0x55e96e3adc35 0x55e96e34073a 0x55e96e3b2f40 0x55e96e3adc35 0x55e96e34073a 0x55e96e3af93b 0x55e96e431a56 0x55e96e3aef

In [2]:
!pip install transformers requests beautifulsoup4 pandas numpy

     |████████████████████████████████| 2.8 MB 5.3 MB/s 
     |████████████████████████████████| 3.3 MB 57.5 MB/s 
     |████████████████████████████████| 636 kB 59.3 MB/s 
     |████████████████████████████████| 895 kB 48.2 MB/s 
     |████████████████████████████████| 52 kB 1.4 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [3]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
# import requests
# from bs4 import BeautifulSoup
import re

2. insantiate model
    * the model that used : https://huggingface.co/nlptown/bert-base-multilingual-uncased-sentiment

In [4]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')
model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')


Downloading:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/953 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/872k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/669M [00:00<?, ?B/s]

3. encode and calculate sentiment <br>
input review here!

In [5]:
review2 = "Pretty disappointing. Was told this was one of the highest rated bars in Asia. Waiter didn't even know what a Jameson and coke was along with Hennessy pineapple. Not one star due to the fact that I enjoyed the live music and the decor."
review3 = "One of my favorite bars in Taipei. Solid drinks menu with some very unique selections for a fairly compact selection. They're located in the same building as MQ so you can also bounce between the two. It's a lot different vibe though. You are guided up towards a set of stairs and through the back of a bookshelf into the classy speakeasy. Usually some good jazz in there and sometimes a live ensemble. Weekends they do require a two drink minimum so be ready for about 900-1000NT charge."

tokens1 = tokenizer.encode('I hated this, absolutely the worst', return_tensors='pt')
tokens2 = tokenizer.encode(review2, return_tensors='pt')
tokens3 = tokenizer.encode(review3, return_tensors='pt')

tokens_list = [tokens1, tokens2, tokens3]

for tokens in tokens_list:
    print(tokens)

tensor([[  101,   151, 39487, 10163, 10372,   117, 35925, 10563, 10103, 43060,
           102]])
tensor([[  101, 31897, 31021, 54894, 36592, 10422,   119, 10140, 20917, 10372,
         10140, 10399, 10108, 10103, 17963, 42156, 39931, 10104, 12734,   119,
         41550, 10177, 30557,   112,   162, 12818, 16332, 11523,   143, 96566,
         10110, 16193, 10111, 10140, 12396, 10171, 21614, 16667, 27480, 17029,
         26378,   119, 10497, 10399, 11424, 10875, 10114, 10103, 17772, 10203,
           151, 50644, 10103, 11343, 10838, 10110, 10103, 75219,   119,   102]])
tensor([[  101, 10399, 10108, 11153, 35380, 39931, 10104, 42550,   119, 25164,
         49755, 10107, 43182, 10171, 10970, 12495, 17949, 45919, 10139,   143,
         67353, 41101, 19415,   119, 10578,   112, 11449, 12120, 10104, 10103,
         11714, 12262, 10146,   155, 11561, 10297, 10855, 10743, 10398, 32726,
         12897, 10986, 10103, 10536,   119, 10197,   112,   161,   143, 15632,
         12850, 10934, 11044, 14

In [6]:
for tokens in tokens_list:
    print(tokenizer.decode(tokens[0]))

[CLS] i hated this, absolutely the worst [SEP]
[CLS] pretty disappointing. was told this was one of the highest rated bars in asia. waiter didn't even know what a jameson and coke was along with hennessy pineapple. not one star due to the fact that i enjoyed the live music and the decor. [SEP]
[CLS] one of my favorite bars in taipei. solid drinks menu with some very unique selections for a fairly compact selection. they're located in the same building as mq so you can also bounce between the two. it's a lot different vibe though. you are guided up towards a set of stairs and through the back of a bookshelf into the classy speakeasy. usually some good jazz in there and sometimes a live ensemble. weekends they do require a two drink minimum so be ready for about 900 - 1000nt charge. [SEP]


The output from the model is a one-hot encoded list of scores.
The position with the highest score represents the sentiment roting e.g. [0.9,0.2,0.1,-0.2,-0.5] is a roting of 1.

In [30]:
result_list = []
i=0
comment = "review "

for tokens in tokens_list:
    i+=1
    result = model(tokens)
    print("\n"+comment+str(i)+":")
    print(result.logits)
    rating = int(torch.argmax(result.logits))+1
    print("rating score:"+ str(rating))


review 1:
tensor([[ 4.8750,  1.7880, -0.8356, -3.0027, -2.0727]],
       grad_fn=<AddmmBackward>)
rating score:1

review 2:
tensor([[ 2.7600,  2.6253,  0.2569, -1.2443, -3.7493]],
       grad_fn=<AddmmBackward>)
rating score:1

review 3:
tensor([[-3.7995, -2.8596, -0.3316,  3.0854,  3.0438]],
       grad_fn=<AddmmBackward>)
rating score:4
